apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    tier: database
    component: mongodb
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      project: roboshop
      tier: database
      component: mongodb
  template:
    metadata:
      labels:
        project: roboshop
        tier: database
        component: mongodb
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.deployment.imageName }}:{{ .Values.deployment.imageVersion }}"

